### PR TITLE
Add cypress framework with typescript support

### LINKED ISSUE #76: Choose framework for end-to-end frontend testing

### PR DESCRIPTION
**Pull request by sherlockq**
Resolves #76 
1. use `yarn cypress-run` to run all the e2e tests
2. use `yarn cypress open` to show the gui
3. use headless mode by default
4. also fix existing e2e test from enric due to introduction of semantic-ui

### CODE REVIEW

**Comment by jmir17** [comment]
image
Tests don't pass in server mode

**Comment by jmir17** [comment]
Dependencies for a server: `sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2`

**Comment by sherlockq** [comment]
> Dependencies for a server: `sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2`

Thanks for all the suggestion. It's fixed now. And I also updated the comment.

**Comment by jmir17** [comment]
image
I don't want to be picky, but only one of the test is passing. Please fix. Sorry and thank you!

**Comment by sherlockq** [comment]
Haha that's a really tough one since we realize that an asynchronous call has a chance to break tests. I will just comment out all tests and just include framework in this pr.

**Comment by sherlockq** [comment]
@jmir17 I just remove that unstable testcase in this branch. It should be all good now. Sorry for all the mess.

**Pull request merged**
